import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },
  paper: {
    padding: theme.spacing(2),
    textAlign: "center",
    color: theme.palette.text.secondary,
  },

  wrapperEach: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    // margin: "2rem",
    textAlign: "center",
  },
  seat: {
    borderRadius: "3px",
    backgroundColor: "rgba(62,81, 93)",
    display: "inline-block",
    padding: "0rem 0.3rem",
    position: "relative",
    margin: "0.5rem 0.65rem",
    maxHeight: "0.8rem",
    maxWidth: "12px",
    cursor: "pointer",
    "&:before": {
      content: `"\u00a0\u00a0"`,
      position: "absolute",
      borderRadius: "2.5px 2.5px 5px 5px",
      bottom: "-76%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      maxHeight: "0.8rem",
      padding: "0rem 0.45rem",
      backgroundColor: "#fff",
      width: "100%",
      borderLeft: "2px solid rgba(62,81, 93)",
      borderRight: "2px solid rgba(62,81, 93)",
      borderBottom: "2px solid rgba(62,81, 93)",
      zIndex: "-1",
    },
  },
  seatVip: {
    borderRadius: "3px",
    backgroundColor: "rgb(247, 181, 0)",
    display: "inline-block",
    padding: "0rem 0.3rem",
    position: "relative",
    margin: "0.5rem 0.65rem",
    maxHeight: "0.8rem",
    maxWidth: "12px",
    cursor: "pointer",
    "&:before": {
      content: `"\u00a0\u00a0"`,
      position: "absolute",
      borderRadius: "2.5px 2.5px 5px 5px",
      bottom: "-76%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      maxHeight: "0.8rem",
      padding: "0rem 0.45rem",
      backgroundColor: "#fff",
      width: "100%",
      borderLeft: "2px solid rgb(247, 181, 0)",
      borderRight: "2px solid rgb(247, 181, 0)",
      borderBottom: "2px solid rgb(247, 181, 0)",
      zIndex: "-1",
    },
  },
  bookingSeat: {
    borderRadius: "3px",
    backgroundColor: "rgb(68, 192, 32)",
    display: "inline-block",
    padding: "0rem 0.3rem",
    position: "relative",
    margin: "0.5rem 0.65rem",
    maxHeight: "0.8rem",
    maxWidth: "12px",
    cursor: "pointer",
    "&:before": {
      content: `"\u00a0\u00a0"`,
      position: "absolute",
      borderRadius: "2.5px 2.5px 5px 5px",
      bottom: "-76%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      maxHeight: "0.8rem",
      padding: "0rem 0.45rem",
      backgroundColor: "#fff",
      width: "100%",
      borderLeft: "2px solid rgb(68, 192, 32)",
      borderRight: "2px solid rgb(68, 192, 32)",
      borderBottom: "2px solid rgb(68, 192, 32)",
      zIndex: "-1",
    },
  },
  bookedSeat: {
    borderRadius: "3px",
    backgroundColor: "rgb(236, 238, 240)",
    display: "inline-block",
    padding: "0rem 0.3rem",
    position: "relative",
    margin: "0.5rem 0.65rem",
    maxHeight: "0.8rem",
    maxWidth: "12px",
    cursor: "pointer",
    "&:before": {
      content: `"\u00a0\u00a0"`,
      position: "absolute",
      borderRadius: "2.5px 2.5px 5px 5px",
      bottom: "-76%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      maxHeight: "0.8rem",
      padding: "0rem 0.45rem",
      backgroundColor: "#fff",
      width: "100%",
      borderLeft: "2px solid rgb(236, 238, 240)",
      borderRight: "2px solid rgb(236, 238, 240)",
      borderBottom: "2px solid rgb(236, 238, 240)",
      zIndex: "-1",
    },
  },
}));
